### ISSUE TITLE
Put validation on email setting.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#1013]
As of now, if we enter the wrong password, hostname, encryption, etc and click on the update button it will show updated successfully.

![image](https://user-images.githubusercontent.com/18435376/79558635-160a3580-80c2-11ea-9a9c-f0c7f4b1a55e.png)

**Comment by bhanu2217** [comment]
Can we use this module from Faveo. In Faveo we have all the checks and validation.
