### ISSUE TITLE
when we are doing payment manually and not selecting any invoice then it showing payment saved

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#1021]
when we are doing payment manually and not selecting any invoice then it showing payment saved
It should not happen without an invoice.
![image](https://user-images.githubusercontent.com/18435376/79957123-c3a08e80-849e-11ea-8ae3-b2f9ec604432.png)

**Comment by ashu555** [comment]
@SarfrazS  This amount if no invoice is selected goes to extra payment in case if somebody wants to pay in advance. After he purchases the product, we can link extra payment to the invoice from edit payment section.
