### ISSUE TITLE
Not able to install on server with port no 21, 22 and 2083. Please see the below gif.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#1028]
I entered server IP and domain but not able to install it. Please may know which IP and port no I can use for the server.
![fb login](https://user-images.githubusercontent.com/18435376/80339345-10f47580-887c-11ea-9deb-e977b0f44c0d.gif)

**Comment by mverma16** [comment]
Does not look like an issue to me, General usage of ports
21: ftp
22: ssh
2083: cpanel

so if these ports are not listening for MySQL connection installation won't proceed. What's the issue in that?

**Comment by avinash403** [comment]
I am closing this issue as it looks like a misunderstanding. Please reopen if any concerns
