### ISSUE TITLE
Client Panel - My Account Page UI

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1049]
This is the UI after user logs in

Compare with this UI below
![Screenshot 2020-05-01 at 4 29 36 PM](https://user-images.githubusercontent.com/240898/80801093-fb0ee980-8bc8-11ea-99af-e7f5ac7be1d2.png)

**Things to Note:**

- Menu/Navigation in the sidebar, which has clear heading and different background color that differentiate is from page background-color
- The menu/navigation has parent and child element
- There are two columns, one for navigation and another for content.
   - Both have different background then page background to create contrast
- Currently, in our My profile page, we have inserted three functionality
   - Profile edit
   - Change password
   - 2FA
- I would ideally separate them and make them as parent-child relationship

**Comment by avinash403** [comment]
how does this look in mobile?

**Comment by avinash403** [comment]
We should start taking inspirations from multiple places and either follow a theme or think our own design. Copying portions from everywhere will make it look like Ranvir Kapoor.
I won't mind even if we shift to some new theme but getting these kind of semi-useful ideas will just delay the things which need more attention
