### ISSUE TITLE
Disallow to change invoice total

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1051]
Invoice edit should allow editing the elements of the invoice. Currently, we allow changing the invoice total.

The invoice edit page needs lot more thing and needs lot more work

Invoice create and edit page should ideally look like this

![Screenshot 2020-05-02 at 9 40 36 AM](https://user-images.githubusercontent.com/240898/80854857-04e02d80-8c59-11ea-87a6-1d430c2d8b53.png)

The total has to be auto-calculated based on the product price. Product price can be changed but not the total.

**Comment by bhanu2217** [comment]
Related #1052

**Comment by bhanu2217** [comment]
Invoice/Renewal module needs to be rebuilt and made more user friendly

Details: https://docs.google.com/document/d/174PWa5lw7y54KqWwpqhp6mExrm9DaSrbXRCYLIVLTVo/edit#

**Comment by sowmiyasubramaniyan** [comment]
It is working fine.so I'm closing this issue.
