### ISSUE TITLE
Invoice values not vanished after saving invoice and alert message showing differently for generate invoice page

### ISSUE THREAD

**Issue by shruti376** [ladybirdweb/agora-invoicing-community#1536]
- [ ] Invoice values not vanished after saving invoice
![Screenshot_66](https://user-images.githubusercontent.com/70562855/100743741-bf5c2c80-3402-11eb-8db9-59faf55956b0.png)

- [ ] Alert message showing different in generate invoice as compared to others alert in billing
![Screenshot_67](https://user-images.githubusercontent.com/70562855/100744009-1f52d300-3403-11eb-80ba-508c2581df15.png)

**Comment by bhanu2217** [comment]
We are looking forward to change the complete invoice module https://docs.google.com/document/d/174PWa5lw7y54KqWwpqhp6mExrm9DaSrbXRCYLIVLTVo/edit#

**Comment by sandesh556** [comment]
> We are looking forward to change the complete invoice module https://docs.google.com/document/d/174PWa5lw7y54KqWwpqhp6mExrm9DaSrbXRCYLIVLTVo/edit#

@bhanu2217 are looking to change this module? @sowmiyasubramaniyan is gonna start working on this bug
