### ISSUE TITLE
Installation path/installation details showing only one record.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#1667]
Step to replicate
Install Helpdesk more than one with the same License key.
Now go to the client panel open order and check the installation path how many are showing. only one is showing. It should show all.
![image](https://user-images.githubusercontent.com/18435376/142862040-77eb5b81-b67a-467c-8567-219a430c7bf9.png)

**Comment by sandesh556** [comment]
This has been fixed and merged with license manager

**Comment by sowmiyasubramaniyan** [comment]
Below is the P.R link:
https://github.com/ladybirdweb/agora-license-manager/pull/16

**Comment by bhanu2217** [comment]
Is this issue resolved or pending?
