### ISSUE TITLE
Session token in URL

### ISSUE THREAD

**Issue by LILLYVIMAL** [ladybirdweb/agora-invoicing-community#1673]
REQUEST:

GET /get-code?country_id=PK&_token=n4EDmslIjOF01LjwzUKG5blc0q8pbYbmyJydNswz HTTP/1.1
Host: billing.faveohelpdesk.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
X-CSRF-TOKEN: n4EDmslIjOF01LjwzUKG5blc0q8pbYbmyJydNswz
X-Requested-With: XMLHttpRequest
Connection: close
Referer: https://billing.faveohelpdesk.com/login
Cookie: visid_incap_2487666=bBjtgg+iQqWzI+W+9ixJdvozEmEAAAAAQUIPAAAAAAAUBHxDeb7aWql5PDrxR1hY; incap_ses_501_2487666=I7LAK5IdHmADC3OiPOnzBvszEmEAAAAAGNWsRDlzu+h+xkGWX5R4sw==; incap_ses_778_2487666=DdeSMzH/zTFCrGsyTgPMCgI0EmEAAAAA6KbatGALnhqle6JQHBQomg==; XSRF-TOKEN=eyJpdiI6IlF4OCtKN0UrQWViVU45T1A3YWdZY3c9PSIsInZhbHVlIjoiMzBJdlZ6SkV4UFQrMmF5ckxyNjdIUnhDRVFKV2M5K0dGd1Q3aUNBR3dETW1NaTAzb09YNm0rUnJIYUVEVjZOMCIsIm1hYyI6ImM0ZDAxZThhNzY0NWMzNWE2YTQ2MGRlNmY1ZDYwODgxNjdmNmJjYWEyYmJlOTA3ZDQ4NDFhZTZlZDBlMGQ3NTgifQ%3D%3D; laravel_session=j2PdaLAKj6UjK6sJuCT3WtqN2hw4YtG3wuOhblyB
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin

RESPONSE:

HTTP/1.1 200 OK
Date: Tue, 10 Aug 2021 08:09:02 GMT
Server: Apache
Cache-Control: no-cache, private
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Set-Cookie: XSRF-TOKEN=eyJpdiI6Ii95M0pRTlB2dldBUUFCR1pacSs2aFE9PSIsInZhbHVlIjoiT3hNWkJsd01wQ3BwbktkNndFTFczT0hsWGhlWXUvVUxPdFYxNzBkSWRtY25hZ1B1OXV4a0tISEs2b3F6WlBpSiIsIm1hYyI6IjE4MDUzZWQzNGIyZGM1OWYzYWVlNGVkMWVkYmFmY2ExZDAyYzNhMDAxZjdkNTY5YjY3MjY5ODdlNmNiMzA4MjcifQ%3D%3D; expires=Tue, 10-Aug-2021 10:09:02 GMT; Max-Age=7200; path=/
Set-Cookie: laravel_session=j2PdaLAKj6UjK6sJuCT3WtqN2hw4YtG3wuOhblyB; expires=Tue, 10-Aug-2021 10:09:02 GMT; Max-Age=7200; path=/; httponly
Connection: close
Content-Type: text/html; charset=UTF-8
Content-Length: 2

**Comment by bindu95** [comment]
One day of task
