### ISSUE TITLE
Different Invoice dates shown on View invoice page and Invoice List page

### ISSUE THREAD

**Issue by LILLYVIMAL** [ladybirdweb/agora-invoicing-community#1676]
Login to billing.faveohelpdesk.com
View an invoice and check the date displayed 
Also in All invoice list verify the date(It is displaying the current date)
![image](https://user-images.githubusercontent.com/52568301/147197781-6afde6c8-c9b3-42ed-bed7-cba05150c4be.png)

**Comment by sandesh556** [comment]
This bug has been resolved.
