### ISSUE TITLE
Single Sign on

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1684]
Have single signon option. Use the same code/package as being used in Faveo.
Support single signon for below listed

- Google 
- Github
- Linkedin

These are just few example, support for as many platforms. As we are a B2B platform, there is no need to integrate with platforms like Facebook, instagram which are of more personal(B2C) nature

If someone is signing up through single sign on method, there is no need to send them OTP over email, as these are trusted platforms. Keep in mind email should be captured, If some platform email is not getting captured, then OTP is required to verify that email.

**Comment by bhanu2217** [comment]
- While registration Single sign on will not be integrated.
- Only while login this should work.

**Comment by Gurmeenkour99** [comment]
Estimated development  time 12 to 15  days
6 days - integration  of social-logins
2 days-  maintaining overall flow
5 days - testing cases
