### ISSUE TITLE
Integrate Agora with Jenkins & Codacy

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1694]

**Comment by bhanu2217** [comment]
Faveo integration is also done with Scrutinizer. We can see if we still want to use this or replace this with Codacy or use both?

**Comment by bindu95** [comment]
Need @mverma16 sir help, @sandesh556 will update, will be done in the end once all the pr's ready

**Comment by bhanu2217** [comment]
@sandesh556 Let's please implement this on priority.

**Comment by sandesh556** [comment]
@sowmiyasubramaniyan will be updating the package needed for test cases to run and then after that we need to focus on a release where we clean up and add missing test cases and failing test cases from existing code so that Jenkins integration can start checking and passing PRs

**Comment by bhanu2217** [comment]
We should not start any new work, till Codacy and Jenkin integration is fully functional.

**Comment by sandesh556** [comment]
Done
