### ISSUE TITLE
Registration Form Changes & dependencies associated 

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1706]
Let's make the form bare minimum, easy for the customer to fill
 
Necessary fields to have

- Name
- Phone with country code
- Email
- Password - Need to think if we want to have a single password field or auto-generate the password. No need to have a password and confirm password can be made a single field

**Other Changes:**

- The form is also linked to Mailchimp
- It's important to pass country to Mailchimp, which could be pulled from Mobile country code
- on the View user and edit user or user profile necessary changes need to be done. No need to remove the fields. They are not linked with the registration form but are still part of the user profile and are editable by the user or admin

**Pop Up:**

- Instead of having a separate page for register/login we can change this to pop up
- The pop will show only log in or register form and linking/switching between the two
- Before implementing this, lets create HTML prototype for it 

Build this functionality using API. If the API is being used externally, we should have a security key function for security.

**Do ensure following**

- Clean Code
- Code commenting
- Unit test cases 
- Support for multilingual, even if today we only have English translation. All text should be coming from the language file

**Comment by bindu95** [comment]
@sowmiyasubramaniyan  Please update the below details
START DATE:
END DATE:
