### ISSUE TITLE
Export to CSV, pdf

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1719]
In all the datatables build options for export and choose columns

Places to put this export and column choose option

- User
- Invoice
- Order
- Tenant

**Columns to add**
In the below tables, give option to show additional columns as optional

**User:**
- Order no(comma separated)

**Orders:**
- User Phone no
- User email
- Order Status(Active/inactive) - currently it also shows as label
- User country

**Invoice:**
- User Phone no
- User email
- Order no(comma separated)
- User country

**Tenant:**
- User name
- User Phone no
- User email
- Order no
- Expiry date
- Paid for free order(currently it is also shown as label)

**Comment by bhanu2217** [comment]
**Export All Orders**
All Orders screen - https://billing.faveohelpdesk.com/orders
Add a button to export all orders
Click on export should display a drop down of all available columns as option items
Columns visible in the UI should be preselected
Users can select columns they want to include in Export.

Mandatory columns: Column Name, Organisation name, Phone number, Product, Expiry Date, Email

**Bug**
View All Orders -> Advance search
Bug: "+" button tooltip should read "Expand". Right now for both + and - cases it says Collapse.
<img width="1097" alt="Screenshot 2022-09-16 at 2 45 08 PM" src="https://user-images.githubusercontent.com/1592705/190602925-e495634a-3326-4982-9e83-f7077ae153d9.png">

**Bug: Renew Order -> Save**
Alert message should not be technical. Display a message that conveys the issue so users can make the required change and try again.
<img width="1112" alt="Screenshot 2022-09-16 at 2 46 12 PM" src="https://user-images.githubusercontent.com/1592705/190603269-71c8ce06-ef7b-4e76-ae4d-9fb37ee4abad.png">

**Comment by sowmiyasubramaniyan** [comment]
L.O.E: 5 days
Task Size: L

**Comment by bhanu2217** [comment]
Along with this issue, if we want to complete this also it will be good 
https://github.com/ladybirdweb/agora-invoicing-community/issues/1720

**Comment by bhanu2217** [comment]
Can we think of a common/generic module which will do following

- Export to pdf, xls, csv

**Smart enough to handle:**
- Large size file export
- Notifications on completion/generation of export
- Link expiry after a while
- Auto deletion of temporary files after certain time duration 

**Other details:**
- Any place on the system, where we need to export data, we will use this module. 

Look at Faveo >> Management report to see how it handles the data

**Comment by sowmiyasubramaniyan** [comment]
- [ ] R&D on this export.
- [ ] Implement it in the user table.
- [ ] Implement it in the invoice table.
- [ ] Implement it in the order table.

**Comment by sowmiyasubramaniyan** [comment]
Start Date: 14-05-2024
