### ISSUE TITLE
Option to add or remove columns from data tables

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1720]
**ToDO:**
- These selections should be saved in cache memory
- Need to implement throughout the system 
- Compare this feature in Snipe IT

**Comment by sowmiyasubramaniyan** [comment]
Along with this issue, completing this issue also
https://github.com/ladybirdweb/agora-invoicing-community/issues/1719

**Comment by sowmiyasubramaniyan** [comment]
Start Date: 08-05-2024
End Date: 10-05-2024
