### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by FrankArisah** [ladybirdweb/agora-invoicing-community#1749]
I'm getting 
Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs)
when finishing the installation process and i also can't do migrations

**Comment by sandesh556** [comment]
> I'm getting Declaration of Doctrine\DBAL\Driver\PDOConnection::query() must be compatible with PDO::query(string $query, ?int $fetchMode = null, mixed ...$fetchModeArgs) when finishing the installation process and i also can't do migrations

Do run composer update and if it's working.
