### ISSUE TITLE
License reissuing is not working

### ISSUE THREAD

**Issue by Vikas-Gandral** [ladybirdweb/agora-invoicing-community#1767]
After reissuing the license from the billing portal as admin, the client is still not able to use the same License code after getting the below error:
![image](https://user-images.githubusercontent.com/94115042/168092986-ec8d91b9-41d1-454b-9e78-45b46dd4a766.png)

To get it to work for the client, we have increased the installation limit to 3 and after that, it worked
Below is the client billing link:
https://billing.faveohelpdesk.com/orders/7998

Now, the client is able to access Faveo (through this link: https://helpdesk.plymouthplace.us)after the above process
![image](https://user-images.githubusercontent.com/94115042/168093801-dd208f5f-98d9-4b17-941b-af4dcdd4df2c.png)

But still, under installation path, there is nothing captured
![image](https://user-images.githubusercontent.com/94115042/168094144-dbfaa8ba-654d-43cd-a027-9cc6198ff3b5.png)

**Comment by sowmiyasubramaniyan** [comment]
Below is the P.R link :                                                                                                                                                                                                  
https://github.com/ladybirdweb/agora-license-manager/pull/43

**Comment by bhanu2217** [comment]
Is this issue resolved or pending?

**Comment by sowmiyasubramaniyan** [comment]
The below is the P.R for this:
   https://github.com/ladybirdweb/agora-license-manager/pull/43

**Comment by bhanu2217** [comment]
@SarfrazS is this is not a issue anymore. Lets please test and close this

**Comment by DhanyaChengappa** [comment]
@SarfrazS Please check if this issue is still valid

**Comment by SarfrazS** [comment]
As of now, Reissue License working fine. Not an issue so I'm closing.
