### ISSUE TITLE
Cloud licensing 

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1795]
Allow to add/remove users/agent from cloud order.

**Comment by sandesh556** [comment]
Also in this, if a client purchases the product with 5 agents uses it, and then expires, after that client renews with 4 agents. i have to remove one agent from the cloud right? so how do I choose which agent to remove?

**Comment by bhanu2217** [comment]
> Also in this, if a client purchases the product with 5 agents uses it, and then expires, after that client renews with 4 agents. i have to remove one agent from the cloud right? so how do I choose which agent to remove? or do we make the client decide before renewal?

**For downgrade:**
- The customer should first remove one agent and then request a downgrade.
- Without agent removal downgrade is not possible in case the customer is using all the agents purchased
- We could also allow the user to schedule the agent removal on the day or day before the renewal. This is when they have paid for e.g 30 days, we allow them to use the system for 30 days and on the last date we remove the user customer has provided and also down grade the order
