### ISSUE TITLE
Product Renewal URL

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1816]
Create a URL to renew a product

**Features:**

- This URL can be shown in Faveo system or other system where Agora is integrated
- This URL will redirect to billing page where product can be renewed
  - If the user is not logged in to billing, it will first redirect to login page and then renewal page after successful login
 - Define parameters on what basis this URL can be generated
   - e.g Installation URL, Product Key, order id etc  

**Purpose:**

- When a particular product has expired to show renewal message and CTA within the Faveo system or other system with Agora integrated to make renewal simpler & easier

**Future changes:**

- _Optional:_ On the renewal pages even show option to upgrade the product or buy add ons to the product. 

**Faveo Github issue No:** #11599

**Comment by sandesh556** [comment]
@bhanu2217 we don't have a renewal URL, since it is a simple pop-up. But the thing we can do is redirect them to my orders page where they will see the renewal and upgrade button
![image](https://user-images.githubusercontent.com/79452740/208810018-20b4f43a-e8aa-4247-b27a-43af48e86f65.png)

**Comment by sandesh556** [comment]
Also if we rewrite the module and create a URL, then we don't have an order number to redirect too since faveo doesn't store order numbers of any sort. I would suggest keep the renewal module as it is, only change that should be added is auto-renewal
