### ISSUE TITLE
Reset password link issue

### ISSUE THREAD

**Issue by Sheetal34** [ladybirdweb/agora-invoicing-community#1866]
I successfully reset my password, but again I click on the reset link, navigating to forgot password page.
![image](https://user-images.githubusercontent.com/92353368/179693159-3cdaa7ee-1909-48a7-9eeb-efc139047f47.png)
![image](https://user-images.githubusercontent.com/92353368/179693195-19caed70-8220-4618-b017-5e3ac9d9ed57.png)

**Comment by bhanu2217** [comment]
The Forgot password link should expire based on

- Time. Valid for maximum of 60 minutes
- After being used

**Comment by DhanyaChengappa** [comment]
@sowmiyasubramaniyan  Lets remove the Oh Snap and the icon from all validation error messages.
The icon can be displayed only for security alerts.
