### ISSUE TITLE
Password field validation issue

### ISSUE THREAD

**Issue by Sheetal34** [ladybirdweb/agora-invoicing-community#1868]
Showing reset password page like this
Why we are writing validation at the top, we need to show validation under password fields, if we are giving any invalid input in password fields.

![image](https://user-images.githubusercontent.com/92353368/179701955-ad5d38f1-97bb-41e0-a46a-5f5a9d3f5e24.png)

**Comment by SarfrazS** [comment]
> Showing reset password page like this Why we are writing validation at the top, we need to show validation under password fields, if we are giving any invalid input in password fields.
> 
> ![image](https://user-images.githubusercontent.com/92353368/179701955-ad5d38f1-97bb-41e0-a46a-5f5a9d3f5e24.png)

It's not an issue. So I'm closing this issue.
