### ISSUE TITLE
Issues related to uploading of logo from the system settings

### ISSUE THREAD

**Issue by priyadarshini2101** [ladybirdweb/agora-invoicing-community#1875]
- [ ] Issue 1:When the file uploaded is of type txt or some other unsupported format for either of them, Admin Panel logo/Favicon/Client Panel logo. The alert message is displaying. But, the files uploaded to these are all getting vanished.

- [ ] Issue 2:When the logo is deleted for either Admin Panel logo/Favicon/Client Panel logo, the API is not showing.

jul20logo

![jul20logo](https://user-images.githubusercontent.com/91872895/179977223-7926952e-cd23-4dce-9fd0-d53158367d5a.jpg)

- [ ] Issue 3:When the same logo is uploaded for Admin Panel logo/Favicon/Client Panel logo, and try to delete the logo of Admin Panel, the same logo is uploaded in other places the images are breaking.

- [ ] Issue 4:Popup alert message for Deletion of logo is not user-friendly.

- [ ] Issue 5:Alert messages are not vanishing after displaying, staying for a long.
- [ ] Issue 6:  Admin Panel > System settings
Select the admin panel logo and update. Admin panel logo showing on the dashboard.
Now click on the delete icon and delete the admin panel logo. Without clicking on update, the admin panel logo will be removed from the dashboard.
image #2019

**Comment by Sheetal34** [comment]
Below is the test cases sheet for the issue
https://docs.google.com/spreadsheets/d/1u0_i_ujWc9AcXrnAvsG72VjcQpj87azH0P9edTQV-iA/edit#gid=486009627
