### ISSUE TITLE
Installer-Application name Issue

### ISSUE THREAD

**Issue by priyadarshini2101** [ladybirdweb/agora-invoicing-community#1876]
After removing the application name text field from the agora installation, still, the App name is showing with an empty value in the .env file.

![jul21app issue](https://user-images.githubusercontent.com/91872895/180154602-1fa58e9e-1809-48f9-8025-7b8dd047d943.jpg)

**Comment by bhanu2217** [comment]
As there is a issue created here closing this one
https://github.com/ladybirdweb/agora-invoicing-community/issues/3067
