### ISSUE TITLE
Cart and Checkout screen enhancements

### ISSUE THREAD

**Issue by DhanyaChengappa** [ladybirdweb/agora-invoicing-community#1897]
**Highlight Cart Color**
Cart color should change to a different color when items are added to cart. Will help make Call to Action clear. 
Need to collaborate with a frontend developer here.

**Pricing screen -> Refresh Cart Count**
Steps:
1. Click on "Order Now". User is navigated to Cart screen
2. Click on browser back button to navigate back to pricing screen
3. Cart items count is not updated. Updates only when refresh is clicked. 
This should be fixed.

**Cart**
https://billing.faveohelpdesk.com/show/cart

- Add separate Agent and Quantity columns
Column order should be Product,Price, Agents, Quantity, Subtotal

- Agent/Quantity count should be Editable
Agent and Quantity should be editable. Set a maximum limit for each.

- Column Headers
Column title should be common for all entries in cart. Do not add a separate header for each row

**Checkout**
https://billing.faveohelpdesk.com/checkout
UI should be similar to Cart screen UI. colors, borders etc

**Comment by bhanu2217** [comment]
Also check point no: 3, page no 6 here https://docs.google.com/document/d/1L3qtdf02IND1MTSfPItfLGtgrrVJrMz13uF3clX2hVY/edit#

**Comment by sowmiyasubramaniyan** [comment]
L.O.E: 2 day
Task Size: M
