### ISSUE TITLE
Auto renewal 

### ISSUE THREAD

**Issue by DhanyaChengappa** [ladybirdweb/agora-invoicing-community#1899]
Customers can auto-renew license 
1. Monthly 
2. Bi-Yearly
3. Yearly
Give customers an option to auto-renew by saving their card details.

**Automatic Payment Regulations in India**
1. Card issuer should support automatic payments
2. All automatic payments that use cards / wallets / Unified Payments Interface are subject to the [Reserve Bank of India e-mandate notification](https://www.rbi.org.in/Scripts/NotificationUser.aspx?Id=12051&Mode=0)

**Use cases to cover:**

Notify customer a day or two before billing cycle. This allows the customer to cancel if they no longer wish to use the service.

**Recurring Payment failure**
1. Send a mail to the customer asking them to update payment
2. Display a message in customer dashboard at the top with button option to auto renew. If user does not act on it even after 10 sessions/1 month, whichever is later, display another button "I don't want to renew my license". Remove the ticker once user clicks the cancel button.
3. Create a section in Faveo team's agent panel to display failed payments so the Accounts team can contact the customer.

**Documentation**
1. FAQ should cover how to cancel an automatic payment

**Comment by bhanu2217** [comment]
Detailed requirement

https://docs.google.com/document/d/1d97IZzufbsoFHZyS8mg6S9nOjZI2eP5aAVHKwC06nPY/edit#heading=h.622u64wbkry1

**Comment by sowmiyasubramaniyan** [comment]
R&D time: 2 days
Expected development LOE: 8 days
