### ISSUE TITLE
Order Search

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1930]
Check if this feature is already existing, if not develop it

Search order based on

- Paid or Unpaid orders in specific time frame of the past they were placed or executed
- Order expired, based on date range of the past when they were expired
- Orders active or inactive
- Order expiring in specific time frame of the future, could be no of days or calendar dates
- Order placed or executed in specific time frame of the past

**Comment by bhanu2217** [comment]
What is missing on the order filters is ability to search orders which are expiring in the future.

**Screenshot:**
<img width="307" alt="Screenshot 2022-12-21 at 9 11 59 PM" src="https://user-images.githubusercontent.com/240898/208945325-b1bc0067-445e-42c7-9adf-97a9a46f6bf8.png">
Ideally here we should have option to search future expiring orders, currently where we only have option for active and expired orders.


On the dashboard we have following widgets:

- Paid Orders Expired in Last 30 days
- Paid Orders Expiring in Next 30 days
- Clients With outdated Product Version

Ideally all these three widget should be using same API of **All order including filters**, which is probably not the case. The data in these 3 widgets should be fetched through the filters.

**Comment by sowmiyasubramaniyan** [comment]
It is done by the below P.R :
https://github.com/ladybirdweb/agora-invoicing-community/pull/2097
