### ISSUE TITLE
New API's - Product integration

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#1931]
**For product integration:**
- Check if user is using latest version of a specific product which is installed. This API is being called from within the product
- Check if user has valid subscription of a product.  This API is being called from within the product

All the API's documentation should be published on Github Wiki

**Comment by bhanu2217** [comment]
Regarding product integration API, these APis are already integrated with Faveo. If we make changes to them, we need to ensure they don't effect the current integration, even if someone is using old version of Faveo the integration should work.

**Comment by sowmiyasubramaniyan** [comment]
L.O.E: 1 day
Task Size: S
