### ISSUE TITLE
BILLING AUTOMATION

### ISSUE THREAD

**Issue by sandesh556** [ladybirdweb/agora-invoicing-community#1943]
**Upgradation of plans**

https://docs.google.com/document/d/1L3qtdf02IND1MTSfPItfLGtgrrVJrMz13uF3clX2hVY/edit

**Comment by bhanu2217** [comment]
@sandesh556 I recommend talking to Shubam and Sidhant to understand the issues they face when customer wants to do product/plan upgrade
