### ISSUE TITLE
 Remove option for  coupon code on checkout page.

### ISSUE THREAD

**Issue by sowmiyasubramaniyan** [ladybirdweb/agora-invoicing-community#2016]
Need Remove option for coupon code after coupon code is applied.

Steps to replicate : 
Add coupon from admin panel > Login from user > Add product in cart > apply coupon at checkout.

**Comment by bhanu2217** [comment]
> 

Is there a reason why we want to implement this?
Sometime if the user is applied wrong coupon, or if they want to try with a different coupon this option is helpful
