### ISSUE TITLE
Purchased product details not displayed in Order and Invoice page

### ISSUE THREAD

**Issue by DhanyaChengappa** [ladybirdweb/agora-invoicing-community#2111]
FHSB customer
Servicedesk enterprise purchased on Feb 14, 2023.
Issue 1: Under Orders -> Invoice list, this purchase invoice is not listed.

Issue 2: All Invoices screen -> filter by customer name

Newly purchased invoice is listed but 

- [ ] price is displayed as 0$ even though this is enterprise software purchase
- [ ] Clicking on the view button, "Sorry something went wrong" page is displayed

<img width="1035" alt="Screenshot 2023-02-21 at 3 13 33 PM" src="https://user-images.githubusercontent.com/1592705/220310657-4059af59-2ecc-480c-a9de-b3512ee8ea9c.png">

<img width="1003" alt="Screenshot 2023-02-21 at 3 13 28 PM" src="https://user-images.githubusercontent.com/1592705/220310676-edee7f4b-4edb-4f4c-9f81-76e017f6c515.png">

<img width="1098" alt="Screenshot 2023-02-21 at 3 13 13 PM" src="https://user-images.githubusercontent.com/1592705/220310694-8e2a6a2b-6b66-4d2b-aad2-d3bb648fa4d6.png">

<img width="749" alt="Screenshot 2023-02-21 at 3 26 23 PM" src="https://user-images.githubusercontent.com/1592705/220311748-8e3e739c-a85d-4547-94fe-dd35f79f94b2.png">

**Comment by sowmiyasubramaniyan** [comment]
The data is not present in the invoice_items table in DB. Either the data was deleted from DB or generated the invoice but failed to create the data in invoice items.

**Comment by bhanu2217** [comment]
> The data is not present in the invoice_items table in DB. Either the data was deleted from DB or generated the invoice but failed to create the data in invoice items.

is this a issue or not? if not lets close it

**Comment by sowmiyasubramaniyan** [comment]
This is fixed.
