### ISSUE TITLE
Remove vendor directory from git

### ISSUE THREAD

**Issue by ajuchacko** [ladybirdweb/agora-invoicing-community#2118]

**Comment by bhanu2217** [comment]
@sandesh556 and @sowmiyasubramaniyan please take a call on this.

**Comment by sandesh556** [comment]
@ajuchacko sorry but we are not going to remove the vendor directory from git, since a lot of people will not prefer running composer install before using this or even developing it.

**Comment by ajuchacko** [comment]
Ok. No problem
