### ISSUE TITLE
Enable development tools

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2175]
Enable following tools 

- **Clockwork package** - https://github.com/itsgoingd/clockwork
- **Query detector** - https://github.com/beyondcode/laravel-query-detector

**Comment by sowmiyasubramaniyan** [comment]
This issue has been created and development is already done. Now that testing is in progress
https://github.com/ladybirdweb/agora-invoicing-community/issues/2180
