### ISSUE TITLE
Adding profiler and N+1 queries debugger

### ISSUE THREAD

**Issue by DhanyaChengappa** [ladybirdweb/agora-invoicing-community#2180]
- [ ] Add profiling to track response time from database and server
- [ ] Enable N+1 queries debugger

**Comment by Sheetal34** [comment]
Below is the test cases sheet for the issue
https://docs.google.com/spreadsheets/d/1u0_i_ujWc9AcXrnAvsG72VjcQpj87azH0P9edTQV-iA/edit#gid=74765019
