### ISSUE TITLE
Icons are not showing  in breadcrumb in the Checkout page

### ISSUE THREAD

**Issue by sowmiyasubramaniyan** [ladybirdweb/agora-invoicing-community#2212]
Check throughout the client panel, if there is a issue with icons.

**Comment by bhanu2217** [comment]
Client Panel icons are still not showing

**Screenshot:**
<img width="213" alt="Screenshot 2023-06-20 at 5 36 33 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/98080353-c534-43a1-9593-d1484e1f60c1">

**Comment by sowmiyasubramaniyan** [comment]
L.O.E: Few Mins
Task Size: XS
