### ISSUE TITLE
Date issue

### ISSUE THREAD

**Issue by Sheetal34** [ladybirdweb/agora-invoicing-community#2245]
- While executing an order
- While generating an invoice
Try to execute the order and generate an invoice at 10:55 pm
In the client, the panel date shows correctly
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/76875e06-f93e-409e-9995-bd6bdec61a3b)
In the admin panel, it's showing incorrect
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/54f69900-fa1d-4211-bc06-080435090ce1)
Generated invoice date 
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/92353368/4308b348-d47e-4160-ae40-17ec322723d3)

**Comment by sowmiyasubramaniyan** [comment]
L.O.E: 1 day
Task Size: S
