### ISSUE TITLE
Billing Price mismatch (Client Portal)

### ISSUE THREAD

**Issue by Skhatr01** [ladybirdweb/agora-invoicing-community#2247]
We have added the prices in billing Plans as per our current prices but whenever a client wants to make payment through their account from billing.faveohelpdesk.com portal it does not reflects the same amount which we have defined in the Portal. I have attached the screenshot for your reference of client and admin Portal 

Admin Panel Screenshot - 
As per the admin panel the price should be $1469 whenever a client needs to renew the product from their billing account 
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/109957325/80687079-5f0f-48b3-bdba-ff578d4d3680)

Client Panel Screenshot - 
As per client panel it only shows the existing prices in the billing 

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/109957325/90d44dd3-019c-4182-a45d-205747910e46)

**Comment by Skhatr01** [comment]
@sowmiyasubramaniyan @DhanyaChengappa Connected with Sowmiya today and we tried to replicate the same on our end but its working fine except the dates showing same for all the invoices which is already detected as a bug. Will keep this under observation need to monitor for sometime if I get any clients will connect with Sowmiya regarding this real time.

**Comment by Skhatr01** [comment]
@sowmiyasubramaniyan @DhanyaChengappa I  have identified if the Invoice is already generated in the billing with an old date and amount and customer click on pay now for that invoice it shows the old price with old amount rather then the new renewal amount. So in order to stream line the process what we can do, If an invoice is generated and customer did not proceed with the payment then the link get expire in 7 days and delete automatically from the system so that he would not be able to pay for that invoice until we raise it again
Once the customer click on pay now link after 7 days it gives a message contact support@faveohelpdesk.com to regenerate invoice or redirect to contact us page

**Comment by bhanu2217** [comment]
Keep in mind this is an open-source, public project. All communication posted here is visible to all.
