### ISSUE TITLE
Cron Language Bug

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2271]
Document: https://docs.google.com/document/d/1L3qtdf02IND1MTSfPItfLGtgrrVJrMz13uF3clX2hVY/edit#
Point no: 12
Page no: 18

**Comment by bhanu2217** [comment]
Need to 1st check if this issue even exist now or is already fixed. If its already fixed, we can close it.

**Comment by sowmiyasubramaniyan** [comment]
It's fixed.

**Comment by Gurmeenkour99** [comment]
Fixed the issue in https://github.com/ladybirdweb/agora-invoicing-community/pull/2791/files.
