### ISSUE TITLE
While purchases and doing Renewal, After enter card details getting this error in both payment gateway.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#2336]
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/549bd267-375e-4c67-aa7a-a3682e25f79a)

**Comment by sowmiyasubramaniyan** [comment]
This problem happens inconsistently, sometimes it occurs. the tester needs to provide specific information about when and where the problem happens exactly.
