### ISSUE TITLE
File upload check

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2337]
- All the file upload in the system should be handled by one single module
- Follow this https://www.opswat.com/blog/file-upload-protection-best-practices

Check where all we have file upload in the system.
Some of the places are listed below, Check throughout once
- User profile image
- Product image
- Product file upload
- Portal logo upload

**Comment by bhanu2217** [comment]
Following location:

- Profile image
- product image
- Portal logo

**Todo:**
- Allow only png, jpeg & jpg file format only
- Set upper maximum size limit
- Store photos outside public(executable) path

**Comment by sandesh556** [comment]
Check if we are following the standards and fix it if not, centralizing the function is more for the development team so creating a separate issue https://github.com/ladybirdweb/agora-invoicing-community/issues/2408
