### ISSUE TITLE
UI Changes - Cloud Pop Up

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2353]
<img width="556" alt="Screenshot 2023-07-11 at 11 24 04 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/ee1a7056-ca2e-4a34-b109-369ff719b7c6">

Check if "Your data centre location is United States" Is centre aligned and spacing on right and left is same

**Comment by sandesh556** [comment]
There is no spacing issue, it's a naked eye illusion
