### ISSUE TITLE
Login page Text field height 

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2354]
<img width="495" alt="Screenshot 2023-07-11 at 11 28 20 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/c112df4f-6647-4684-83b1-9147d53f65ba">

- Height of text field is looking smaller in comparison to other places

May be it's and illusion, please check and confirm once

**Comment by sandesh556** [comment]
There is no issue, verified in a few other forms the margin-bottom is 0.5 rem everywhere. But login form looks fine to me

**Comment by sandesh556** [comment]
manually linking a PR since PR has reached a limit https://github.com/ladybirdweb/agora-invoicing-community/pull/2361
