### ISSUE TITLE
Design different license detail page for cloud & self hosted

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2355]
<img width="1164" alt="Screenshot 2023-07-11 at 11 32 17 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/8b90bf92-23cf-45d9-8ffd-3464f8ad7574">

This needs to be designed both on client and agent panel

**Comment by sandesh556** [comment]
ip has been removed and reissue has been removed from free trail orders
