### ISSUE TITLE
Time mis match

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2360]
- Check time on all the pages throughout the system
- While saving time to database, time should be converted from user time zone to UTC
- While fetching time from database, time should be converted from UTC to user time zone
- Check client panel, agent panel, admin panel

**Comment by bhanu2217** [comment]
Ideally there should be a centralised function/class to do time conversion. It shouldn't be handled at each screen level

**Comment by sandesh556** [comment]
Even this I think we already use a centralized function to do it check that, But if not centralized we will add it in the next release but wherever the time mismatch is happening fix that in this issue creating a new issue to revamp https://github.com/ladybirdweb/agora-invoicing-community/issues/2409

**Comment by Gurmeenkour99** [comment]
Estimated Time: 4 to 5 days
Understanding existing code flow  and the issue: 2 days
Development ,debugging and testing: 2 to 3 days

**Comment by bhanu2217** [comment]
**Option 1:**

- Save user, agent, admin time zone on their profile, in user table in the database 
- On first time creation of user. select time zone based on the IP address country 
- User can change their time zone from their profile or admins can change it for them 

**Option 2:** 

- Save user, agent, admin time zone on their profile, in user table in the database 
- On first time creation of user. select time zone based on the user's system time zone
- User can change their time zone from their profile or admins can change it for them 
- Agora to detect if users database time zone is different from users system timezone, to give option to user to update database timezone
