### ISSUE TITLE
Cloud Expiry email text has to be changed

### ISSUE THREAD

**Issue by DhanyaChengappa** [ladybirdweb/agora-invoicing-community#2378]
- [ ] Change the text

<img width="860" alt="Screenshot 2023-07-19 at 11 38 20 AM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/1592705/ac7c306f-478f-4aa9-a9cc-3273ed63a441">

- [ ] I did not get a reminder that my trial period is expiring soon. We should add this if it currently isn't there

**Comment by bhanu2217** [comment]
Some places subject said GONNA expire. Lets not use slag and use simple, clear english

**Comment by sandesh556** [comment]
We don't have to make a release or code changes unless you want shortcodes, Any text changes can be directly be added to the template itself
