### ISSUE TITLE
Auto calculate the invoice price for per agent based on base price

### ISSUE THREAD

**Issue by sandesh556** [ladybirdweb/agora-invoicing-community#2390]
The form when you choose the product auto-fills the base price and the number of agents by default is one agent, Now when the user increases the number of agents the price has to be calculated based on the base price * the agents chosen. But also editable which helps us to calculate the price and also edit if required

**Comment by bhanu2217** [comment]
Please put in a description of what needs to be done here. Link it with the project and milestone.
