### ISSUE TITLE
Faveo Cloud setting page UI design

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2431]
This is the page where we can do following

- Change domain for cloud URL's
- Upgrade/downgrade product

@Sakthi002 see if you can help with better design. We can even involve Shivaleela for prototype.

**Comment by sandesh556** [comment]
![Screen Shot 2023-08-03 at 5 57 26 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/98c8afe8-c844-4fb0-850f-e0526b279354)
![Screen Shot 2023-08-03 at 6 15 32 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/5ace75be-be55-4e6d-8c6a-08af09159538)
![Screen Shot 2023-08-03 at 6 16 12 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/fd74490c-5b13-49c2-91bb-6eff76f52513)
![Screen Shot 2023-08-03 at 6 16 53 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/e4005b0f-f459-4140-92f0-b79d7fbe2e03)
![Screen Shot 2023-08-03 at 6 17 22 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/3d0f978d-35ad-4f18-a967-91d154a2a3a6)
![Screen Shot 2023-08-03 at 6 17 45 PM](https://github.com/ladybirdweb/agora-invoicing-community/assets/79452740/5d5ea745-c80c-4950-a32f-e370cbac0b1b)
