### ISSUE TITLE
No Data Available Message 

### ISSUE THREAD

**Issue by Gurmeenkour99** [ladybirdweb/agora-invoicing-community#2437]
In My Invoice page there is no message displaying if there is no data data available .

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/d4a474bf-89fa-4ecd-a3b0-10a94ee8ca23)

**Comment by bhanu2217** [comment]
**Feedback:**

- When user logs in, this is the page they hit.
- If there are no invoices the page looks like this, The header for table is showing

**Changes:**
- Display some message in the datatable like no records found or something like that?
- Make the page longer
