### ISSUE TITLE
Text and Image are Overlapping

### ISSUE THREAD

**Issue by Gurmeenkour99** [ladybirdweb/agora-invoicing-community#2438]
On select of any name the image of user and name is overlapping. There is no space .

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/45eff004-ecf1-41fe-b9da-b008f19c42e2)

**Comment by bhanu2217** [comment]
**Feedback:**

- Have at least a character gap between the image and text and if required have couple of characters gap to make it look more aesthetically pleasing.
