### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by Gurmeenkour99** [ladybirdweb/agora-invoicing-community#2439]
There is no space between the buttons, we can also enhance UI .

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/65616b4f-30ec-4831-a7c4-cd3acfa17f2b)

**Comment by bhanu2217** [comment]
@Gurmeenkour99 On 2nd thought, Please involve @Sakthi002 into this page design also. Check with him his availability.
