### ISSUE TITLE
No validation while creating coupon with percentage.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#2458]
There is no validation we are able to create a coupon with 200 percent which is wrong. it should be 100 percent.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/d538b55f-8c31-4fe1-b0ac-f3c69155deef)

**Comment by DhanyaChengappa** [comment]
**Demo corrections**

- [ ] Reduce cell width

- [ ] Change label to Discount value

- [ ] Change label to Number of uses

- [ ] Add an "i" for both mentioned above and explain exactly what this is for

**Comment by bhanu2217** [comment]
**Issues:**

- Value and uses are accepting alphabetic characters also
- The validation messages displayed on top, doesn't make it clear the message is for which field. Ideally that feild should have been highlighted. This should follow symmetry throughout the project
- No option to select all products
