### ISSUE TITLE
Invoice UI Issues

### ISSUE THREAD

**Issue by Gurmeenkour99** [ladybirdweb/agora-invoicing-community#2493]
- [x] On stripe payment gateway interface , on submit add space between loader and processing and remove please wait. Also the loading image and text should be vertically middle aligned 
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/da375eb5-1af6-45ce-9b6a-c910695e827f)

- [x] On checkout page we can remove the green background and the cross icon at the top right coroner , In the table make the first row highlighted , add space after semi columns and make all the text after semicolon regular rather than bold , Remove continue shopping option .
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/7e730262-87c1-4f9e-b722-7f070b6895d1)

- [x] We can move the remove (cross icon) at the top corners rather than in the middle.
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/3dc38cee-78f8-416b-b1f9-a636064c18c8)

- [x] Add space between  cart Total box and text. Change heading of the box to Cart Total
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/129725907/5be3daf2-27f9-4c44-b478-2fcc3d96152d)

**Comment by DhanyaChengappa** [comment]
@Gurmeenkour99 
**Demo corrections**

- [ ] Add more space between Loader and text
- [ ] Loder icon looks bottom aligned compared to text. Ensure they are vertically centered
<img width="145" alt="Screenshot 2023-09-01 at 3 52 15 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/1592705/03b742fd-40a6-427e-b59e-136b3e73a5bc">

- [ ] Date and email row gaps is more
- [ ] only thank you line text should be in bold, rest can be plain text
- [ ] Some places semicolon is bold and other places not bold

<img width="444" alt="Screenshot 2023-09-01 at 3 56 04 PM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/1592705/6183c002-8e5d-44e6-a4c3-8d1dfbb920c2">
