### ISSUE TITLE
In Agora installer give option to select timezone and make it same installer as faveo.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#2495]

**Comment by bhanu2217** [comment]
Ideally i would remove the current installer and use the same installer used in Faveo Helpdesk

**Comment by bhanu2217** [comment]
If we are working on this, following issues can  be ignored and closed

 - https://github.com/ladybirdweb/agora-invoicing-community/issues/2875
 - https://github.com/ladybirdweb/agora-invoicing-community/issues/2857
 - https://github.com/ladybirdweb/agora-invoicing-community/issues/1876

**Comment by bhanu2217** [comment]
As there is a issue created here closing this one
https://github.com/ladybirdweb/agora-invoicing-community/issues/3067
