### ISSUE TITLE
Few small changes

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2593]
The emails which are going out from Contact us page and Request a demo, Country code is missing from the phone no

Invoice page, check colon position, screenshot below. Lets have symmetry. URL: https://billing.faveohelpdesk.com/my-invoice/XXX and https://billing.faveohelpdesk.com/invoices/show?invoiceid=xxx

<img width="105" alt="Screenshot 2023-09-08 at 10 02 58 AM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/798a786c-0246-4bd6-9c20-39cb2fb9ce65">

Contact us page, phone no before + leave one character gap. Screenshot below
<img width="89" alt="Screenshot 2023-09-08 at 10 04 13 AM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/44fedaa5-0cec-4be1-804c-063a1545804b">

**Comment by sowmiyasubramaniyan** [comment]
Issue resolved. I am closing the issue.
