### ISSUE TITLE
Admin User OTP non verified - Unable to login

### ISSUE THREAD

**Issue by kilian099** [ladybirdweb/agora-invoicing-community#2609]
Hi Team,

I have found after I installed and apply a new mobile phone in my admin account. I am no longer access it because I haven't setup yet the OTP verification. Is there any way from DB to reset or remove the token it sets this OTP force verification?

Regards,
Kilian

**Comment by sowmiyasubramaniyan** [comment]
@kilian099 Thank you for reaching out with your query,
There are two ways to bypass the top validation in the users' table: you can change the value from 0 to 1 in the 'mobile_verified' field to enable login, or you can avoid the top verification by disabling the 'msg91_status' in the 'status_settings' table.
