### ISSUE TITLE
Remove duplicate  Australia county name from currency list

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#2631]
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/267e9652-623e-495e-b0d3-b87ca748d2c2)

**Comment by DhanyaChengappa** [comment]
**Demo corrections**

- [ ] currency code and currency symbol text should be centered

**Comment by bhanu2217** [comment]
This issue issue is still not resolved. Re opening the issue
