### ISSUE TITLE
Display the number of unpaid invoices below the header on every page in the client panel.

### ISSUE THREAD

**Issue by sowmiyasubramaniyan** [ladybirdweb/agora-invoicing-community#2659]
**Screenshot:**
<img width="897" alt="Screenshot 2023-10-03 at 11 28 57 AM" src="https://github.com/ladybirdweb/agora-invoicing-community/assets/240898/fbcfbeca-382c-45fb-b86b-b636213771fe">

**Following information can be displayed:**

- **Pending invoices** - Show no of unpaid invoices, when clicked on it to take to the invoice data table and show these pending invoices
- **Order** - Show total no of orders, which clicked, take to order data table 
- **Order Renewal** - Show the count of orders which are due for renewal in next 30 days. When clicked on it, take to data table to show orders which are due for renewal

**Comment by bhanu2217** [comment]
On the client dashboard we are already showing this, i don't think its required to show these widgets on all the pages. We can just check if any widget is missed or to be added.
