### ISSUE TITLE
Search is not working in the order details data table from the admin panel.

### ISSUE THREAD

**Issue by SarfrazS** [ladybirdweb/agora-invoicing-community#2725]
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/18435376/f831aea4-10dd-4c2c-aceb-a703a79151fd)

client panel->my-orders->dowloads
search and sorting not working
![Screenshot from 2023-12-21 11-24-07](https://github.com/ladybirdweb/agora-invoicing-community/assets/96425427/5e7de746-fdb9-4441-881f-817050a59caa)

**Comment by Gurmeenkour99** [comment]
Estimate days 1or2
