### ISSUE TITLE
Purchase Confirmation Email : Knowledgebase Link redirects to Invalid URL

### ISSUE THREAD

**Issue by raghavfaveo** [ladybirdweb/agora-invoicing-community#2751]
When a customer buys a product, they get a Purchase confirmation email.
The email has two issues
1. The Click Here URL is missing for which github already raised
https://github.com/ladybirdweb/agora-invoicing-community/issues/2658

2. Refer to Knowledgebase Link redirects to invalid URL

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/106146976/3530a2c7-cd58-4f0c-93b2-c412ded2fbd1)

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/106146976/347daf81-0fcc-441d-b112-730475f72203)

**Comment by bhanu2217** [comment]
These KB links cannot be part of seeding file. As Agora Invoicing is a product.
These links should be added only to live version of Agora Invoicing being used by Faveo.
