### ISSUE TITLE
Showing currency as INR for non-Indian clients in the user details page

### ISSUE THREAD

**Issue by sowmiyasubramaniyan** [ladybirdweb/agora-invoicing-community#2799]

**Comment by bhanu2217** [comment]
**What currency should be visible on client profile:** The currency that they see store prices in

**Other clarifications:**
Sometime some client ask us to send invoice in their currency
In these cases we should have the option to change the client currency from their profile
Once the currency is changed, new invoices/payments will be in that currency.
Old invoice/payment receipt currency will not change.

That means, its important to show currency in the profile and give option for its change also. This is beyond how automatic assignment of the currency works, that should work the way it is working.

**Comment by sowmiyasubramaniyan** [comment]
We don't have a quotation feature. I will add a way for users to change their currency on the profile edit page. When someone signs up, the default currency is set to INR. Instead, we'll set the currency based on the user's country. When we create the quotation feature, it will let users choose their currency or use a system-available currency from the plans.

**Comment by bhanu2217** [comment]
I don't think we should wait for quotation feature.
Currently we raise invoices for users, we need to have ability to change users currency. I wouldn't remove this feature. I would rather make it working the way i have suggested.
