### ISSUE TITLE
Installer - Software Installation Issue: SQL Error When Truncating Table in MySQL

### ISSUE THREAD

**Issue by m-stankiewicz** [ladybirdweb/agora-invoicing-community#2857]
During the installation of the software:

App Environment: Production
App Log Level: Info
All other settings default
After entering the correct MySQL details and starting the installation, the following message is received:
"Alert! Failed. ×SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a table referenced in a foreign key constraint (invoices.product_groups, CONSTRAINT product_groups_pricing_templates_id_foreign) (Connection: mysql, SQL: truncate table pricing_templates)"

PHP Version: 8.2.14
MySQL Version: 8.0.35
Operating System: Linux Ubuntu 22.04.1

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/47892280/3b5f21fc-0069-4212-85c2-6f5e960dffd0)

**Comment by m-stankiewicz** [comment]
forgot to add. 4.0.0 version

**Comment by bhanu2217** [comment]
As there is a issue created here closing this one
https://github.com/ladybirdweb/agora-invoicing-community/issues/3067
