### ISSUE TITLE
Installer - Installation Issues

### ISSUE THREAD

**Issue by shiekhaasif** [ladybirdweb/agora-invoicing-community#2875]
**1. PHP Version Check:**

Probe shows required PHP v7.3.0, and verifies PHP v8.127 is installed as correct version.
Needs to be mentioned clearly whether we need PHP version > v7.3.0 or v8.1.x

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/101315548/fe4d8fe3-c3ee-4fce-9b70-a3e94898ff33)

**2. Probe Check:**

The probe page has 5 steps, but it does not highlight which step has been performed and which is pending.
There must be a color gradient for the step that is being performed, like it is highlighted for **Environment** > **Database** > **Application**

![agora](https://github.com/ladybirdweb/agora-invoicing-community/assets/101315548/9689eece-0a84-4feb-b971-4fce5e231436)

**3. .env Issue:**

There is no check for .env. if .env is already present, probe is not highlighting it.

**4.  Database Error:**

Database error while migrating tables. The same issue was faced during client installation.

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/101315548/373be9e4-e55f-4bac-a3d2-b2c8343c394a)

**5. Database Version Check:**

We have no checks for MySQL/MariaDB version check, Unlike Faveo which works with Mysql8.0 & MariaDB 10.6, we are not sure about the versions which are supported on Agora.

**6. Special Character Password Error:**

When a Database password includes special characters like **Password@123$#**, This password is taken as the wrong password by the GUI Installer and the user is denied access. The Same password needs to be enclosed in the Single quotes like **'Password@123$#'**, in this case password is treated as correct password.

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/101315548/a625fd30-f030-4290-a62a-31bd2add684f)

**7. Folder Permissions:**

The current File/Folder permissions are not correct from the security point of view. We are giving permission 775 for the Directories which is insecure as groups have full READ, WRITE & EXECUTE Permissions. The permissions must be similar to Faveo Permissions which is:

- 644 for Files
- 755 for Directories

<a href="https://www.guru99.com/file-permissions.html" target="_blank" rel="noopener">Check this article</a> for more details about file permissions.

![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/101315548/32c3647c-e1a5-4d20-8e5b-faa10b6e282b)

**8. Enforce SSL:**

Currently, there is no SSL enforcement in Agora and works without SSL Certificates as well which is not secure from the  Security point of view. SSL must be enforced, Installation must not be completed without without SSL Certificate.

**9. Supervisor Worker File:**

Currently,  we are using the below configuration file for supervisor jobs:

```
[program:billing-Worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /path/to/filesystem/artisan queue:work redis --sleep=3 --tries=3
autostart=true
autorestart=true
numprocs=4
user=webuser
redirect_stderr=true
stdout_logfile=/path/to/filesystem/storage/logs/worker.log


[program:billing-horizon]
process_name=%(program_name)s_%(process_num)02d
command=/usr/local/bin/php /path/to/filesystem/artisan horizon
autostart=true
autorestart=true
user=webuser
redirect_stderr=true
stdout_logfile=/path/to/filesystem/storage/logs/horizon.log
```

We have no explanation for billing-Worker:

- Why is it used? 
- Will agora work without this worker?
- Why are we using 4 Jobs for this worker? Which creates an extra load on the server.

We need to be sure whether it can be removed or it is to be kept.

**Comment by bhanu2217** [comment]
- Lets replace this installer with Faveo installer
- Use new UI from here https://github.com/ladybirdweb/faveo-html-prototype/tree/development/Faveo-Installer

**Comment by sadhasivam-ladybirdweb** [comment]
Modify the current installation process and build a process similar to the Faveo and License Manager.

**Comment by sandesh556** [comment]
So we will use the same installer that we are using in faveo and license here

**Comment by bhanu2217** [comment]
As there is a issue created here closing this one
https://github.com/ladybirdweb/agora-invoicing-community/issues/3067
