### ISSUE TITLE
Stripe payment issue with Indian payments

### ISSUE THREAD

**Issue by sowmiyasubramaniyan** [ladybirdweb/agora-invoicing-community#2897]
![image](https://github.com/ladybirdweb/agora-invoicing-community/assets/96425427/6b9aae9e-8254-4a46-9186-ef9ba52b9440)
We need to update our APIs in Stripe to comply with Indian payment regulations, specifically enabling 3D Secure for card payments, as per the guidelines provided by Stripe (https://support.stripe.com/questions/guide-for-saving-cards-in-india#).
 Also, we need to make the necessary adjustments for both one-time payments and auto-renewing subscriptions API.

**Comment by sowmiyasubramaniyan** [comment]
- [ ] Need to make API changes for manual payments to incorporate 3DS.
- [ ] Need to verify the flow post successful payment, including order, subscription, and payment creation.
- [ ] Need to verify payments within the auto subscription enable function.
- [ ] Require API modifications for subscriptions.

**Comment by bhanu2217** [comment]
There are 2 things here

- Manual Payment
- Auto payment

Do test and check both are working as expected and it should work for all the customers from across the world including India
