### ISSUE TITLE
Razorpay auto renewal not working

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#2925]
There are 2 things here

- Manual Payment
- Auto payment

Do test and check both are working as expected and it should work for all the customers from across the world including India
Need to check for refund money regarding an auto subscription.

**Comment by sowmiyasubramaniyan** [comment]
- [ ] R&D on Razorpay subscription API for alternative methods to detect payments without requiring card details.
- [ ]  code cleanup for the renewal subscription API.
- [ ] code cleanup for the manual payment API.
- [ ] Exploring the feasibility of consolidating both payment gateway functionalities into a single page to avoid redundancy.
 - [ ] Need to write test cases to cover all possible scenarios.
