### ISSUE TITLE
Minor Bugs

### ISSUE THREAD

**Issue by sowmiyasubramaniyan** [ladybirdweb/agora-invoicing-community#2987]
- [x] Mailchimp reCAPTCHA needs to be added.
- [x] Mailchimp's name is not being passed.
- [x] The switch button overlaps in the admin panel order view page.

**Comment by bhanu2217** [comment]
Check following

- On user registration
- User profile update
- User product purchase

When these events occurs data should be updated on mailchimp. Doesn't matter these events occurs because of admin or user actions
