### ISSUE TITLE
Billing portal password reset link still working after reset the password from Billing Profile.

### ISSUE THREAD

**Issue by Anku2155** [ladybirdweb/agora-invoicing-community#3010]
If we reset the password from forgot password option the reset password link is sent to the email. But at the same time, we changed the password from the billing profile. After changing the password go to that reset password link the link is still active.

**Steps to replicate:**
1)  Go to the forgot password page, enter the email address, and click submit.

2)  Check your email inbox, and you will see that you have received a reset password link.  

3)  Now login into your account and update your password from there.

4)  Go to your email inbox and use the reset password link, i.e. change your password from there.

5)  You will be able to see that your password has been changed.

6)  When you update your password from your account, the link that is present in your email ID should automatically expire.

**Expected behavior:**

- The Link should expire if the password is changed from UI at the same time or there should be an option for 2-factor authentication.
- The link should also have some time based validity. If link is not used within that time frame it should expire.
- Compare this functionality with other systems also

**Comment by bhanu2217** [comment]
> If we reset the password from forgot password option the reset password link is sent to the email. But at the same time, we changed the password from the billing profile. After changing the password go to that reset password link the link is still active.
> 
> **Steps to replicate:**
> 
> 1. Go to the forgot password page, enter the email address, and click submit.
> 2. Check your email inbox, and you will see that you have received a reset password link.
> 3. Now login into your account and update your password from there.
> 4. Go to your email inbox and use the reset password link, i.e. change your password from there.
> 5. You will be able to see that your password has been changed.
> 6. When you update your password from your account, the link that is present in your email ID should automatically expire.
> 
> **Expected behavior:**
> 
> * The Link should expire if the password is changed from UI at the same time or there should be an option for 2-factor authentication.
> * The link should also have some time based validity. If link is not used within that time frame it should expire.
> * Compare this functionality with other systems also

I don't think there should be any correlation between change password or forgot password functionality, both are independent.
Below are the scenarios i see for which forgot password link should expire

- The link was used and password was changed
- Based on certain time, e.g link is valid for 60 minutes
