### ISSUE TITLE
Issues reported in v4.0.2.1

### ISSUE THREAD

**Issue by bhanu2217** [ladybirdweb/agora-invoicing-community#3027]
- Duplicate order
- Search and column over lapping in UI

**Comment by SarfrazS** [comment]
1. Duplicate Order/invoice showing.
2. Select Column overlapping.
3. Report setting sidebar UI breaking.
4. The default filter is not there in the user order and invoice

**Comment by SarfrazS** [comment]
Point no 7 all report email notifications coming
![image](https://github.com/user-attachments/assets/60a5f50b-4997-456e-99cd-e573d9012acd)
