### ISSUE TITLE
UI Fixes

### ISSUE THREAD

**Issue by indira15v** [ladybirdweb/agora-invoicing-community#3031]
The UI dropdown in all columns (user,order,invoice and tenants) should be made  uniform some goes shorter
![image](https://github.com/user-attachments/assets/c2afaa86-8842-4654-bda3-ebf7acd767e7)

Also when certain columns are imported there are some default columns that are coming from the DB that needs to be handled better through out the system

**Comment by bhanu2217** [comment]
I don't think this is a issue, based on screen size this will change, on my laptop everything is coming in one line.
