### ISSUE TITLE
Installer should also check for mysql install requirements

### ISSUE THREAD

**Issue by juanluisbaptiste** [ladybirdweb/agora-invoicing-community#746]
Hi,

While following the [installation guide for apache 2.4](https://docs.agorainvoicing.com/installation-with-apache-2-4/) I was having problems with connecting to the database that turned out to be an issue with missing php mysql modules which aren't listed as requirements. I installed php-mysqli and pdo_mysql extensions and the database connection worked.

It would be nice if you add those requirements to the installation guide and the install wizard check requirements page.

**Comment by ashu555** [comment]
Yeah sure, thanks for the suggestion. Will make  a release very soon with those additional checks in place.

**Comment by juanluisbaptiste** [comment]
Excellent, thanks (y)

**Comment by bhanu2217** [comment]
**Action Plane:** Use the same installer CLI and GUI as in Faveo Helpdesk Enterprise

**Comment by juanluisbaptiste** [comment]
> **Action Plane:** Use the same installer CLI and GUI as in Faveo Helpdesk Enterprise

How ? can you point me to the documentation ?

**Comment by bhanu2217** [comment]
@juanluisbaptiste Our team will take care of this implementation. Once done we will update you.
