### ISSUE TITLE
Option to soft delete users

### ISSUE THREAD

**Issue by ashu555** [ladybirdweb/agora-invoicing-community#854]
Cuurently if a user is deleted, his comments on other user profile exists which results in exception. An option for soft deleting should be present in system and if the user is permanently deleted the comment should be linked to other admin.

**Comment by bhanu2217** [comment]
- Put option to soft delete, call it as deactivate
- On complete deletion give option to assign comments etc to different user. Do post a comment saying system assigned all comments from this user to that because of user deletion
