### ISSUE TITLE
In footer, type is mandatory 

### ISSUE THREAD

**Issue by bindu95** [ladybirdweb/agora-invoicing-community#870]
In the footer, a type is mandatory but not specified as mandatory. Please add * symbol to type in widgets

Content is not mandatory but showing *  
Please fix it. If its mandatory throw alert if not remove *

**Comment by sowmiyasubramaniyan** [comment]
![image](https://user-images.githubusercontent.com/96425427/166668517-c278b268-7249-4213-abd0-52bba90b32f7.png)
