### ISSUE TITLE
Alert UI is not good for terms option

### ISSUE THREAD

**Issue by bindu95** [ladybirdweb/agora-invoicing-community#881]
A better option is to disable the submit button until terms checkbox is selected

**STEPS TO REPLICATE:**
Enable "Show Terms on Registration Page" and now try to register a user without accepting the terms. Showing as below
![image](https://user-images.githubusercontent.com/27956111/63941181-a0951a80-ca88-11e9-8e27-d6c35bb93500.png)

**Comment by sowmiyasubramaniyan** [comment]
![image](https://user-images.githubusercontent.com/96425427/166670102-8ef9858e-0941-40d5-9c41-39a73c667b09.png)
