### ISSUE TITLE
Search with full name is not working

### ISSUE THREAD

**Issue by bindu95** [ladybirdweb/agora-invoicing-community#944]
URL: https://billing.faveohelpdesk.com/clients In name field Search for Ron Brown, search result 0
But client exist in the system https://billing.faveohelpdesk.com/clients/4758

**Comment by avinash403** [comment]
Closing this issue, it is working. This functionality has some performance optimisations in https://github.com/ladybirdweb/agora-invoicing-community/pull/1017
